### ISSUE TITLE
Just dosent work...

### ISSUE THREAD

**Issue by Ghdhdhdh** [Raymo111/kahoot-answer-bot#24] opened 2023-01-29 07:38 UTC
PS C:\Users\jacob\Downloads\kahoot-answer-bot-2.2> python3 kbot
name > Jacob
pin > 1233173
quizID > eab4ca4e-e3a7-4672-8cfc-62bd0b93f661
TypeError: As of 3.10, the *loop* parameter was removed from Semaphore() since it is no longer necessary

I have noid

**Comment by Raymo111** [comment] 2023-01-29 23:00
Duplicate of #19.

**Closed** 2023-01-29 23:01 UTC
Labels: duplicate
