### ISSUE TITLE
Doesn't join to kahoots

### ISSUE THREAD

**Issue by MineJOT1** [Raymo111/kahoot-answer-bot#17] opened 2022-01-28 14:46 UTC
So, the bot doesn't join the kahoot but shows the correct answers in the cmd. It worked yesterday, today doesn't join.

**Comment by Raymo111** [comment] 2022-06-01 00:54
Duplicate of #19 (that issue is clearer than this one)

**Closed by Raymo111** 2022-06-01 00:54 UTC
