### ISSUE TITLE
`asyncio.exceptions.CancelledError KeyError: 'answer'`

### ISSUE THREAD

**Issue by judemont** [Raymo111/kahoot-answer-bot#29] opened 2023-04-09 17:24 UTC
Hello,
When I run kbot I have this error : 
```error

name > heey      
pin > 2483188
quizID > c316b5c7-eebe-496f-b0b0-85381c174a62
No accepted answers
Title: Bambi Spring Trivia
Creator: Disney_Official
Desc: Celebrate spring by reliving memorable moments from the classic story of Bambi and his friends. © Disney. All rights reserved. #disney #disneyspring #bambi
Exception in callback TransportBase._connect_done(<Task cancell.../utils.py:22>>)
handle: <Handle TransportBase._connect_done(<Task cancell.../utils.py:22>>)>
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

asyncio.exceptions.CancelledError
Exception in callback WebSocketTransport._receive_done(<Task cancell...ocket.py:224>>)
handle: <Handle WebSocketTransport._receive_done(<Task cancell...ocket.py:224>>)>
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

asyncio.exceptions.CancelledError
KeyError: 'answer'
```

**Comment by sealldeveloper** [comment] 2023-06-20 00:16
I think my pull request may have solved this? Try my branch and see if that fixes it. Also running it with `-d` for debug provides more detail for error reporting.

**Comment by Raymo111** [comment] 2023-06-20 02:27
Duplicate of #16.

**Closed** 2023-06-20 02:27 UTC
Labels: duplicate
