### ISSUE TITLE
Error when attempting join

### ISSUE THREAD

**Issue by aris-a11** [Raymo111/kahoot-answer-bot#18] opened 2022-04-06 02:11 UTC
After filling out the pin and quiz id I am met by the error "TypeError: As of 3.10, the *loop* parameter was removed from Semaphore() since it is no longer necessary" Any help would be welcomed, thank you.

**Comment by QTPah** [comment] 2022-04-10 19:54
I have the same problem.

**Comment by Raymo111** [comment] 2022-06-01 00:53
Duplicate of #19 (that issue is clearer than this one)

**Closed by Raymo111** 2022-06-01 00:53 UTC
